"""sua mensagem

Revision ID: bf26e39bedba
Revises: 9ae543ebe350
Create Date: 2025-06-10 09:43:04.704548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf26e39bedba'
down_revision: Union[str, None] = '9ae543ebe350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('from_user_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('to_user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('messages_ibfk_1'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['to_user_id'], ['id'])
    op.drop_column('messages', 'user_id')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('messages', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_ibfk_1'), 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'to_user_id')
    op.drop_column('messages', 'from_user_id')
    # ### end Alembic commands ###
